### ISSUE TITLE
请求提供requirements.txt

### ISSUE THREAD

**Issue by willy9156** [azmiao/pcrjjc_tw_new#9]
您好，我在执行main.py的 `query()` 时，遇到 `ExtraData: unpack(b) received extra data.` 的错误，不确定是否套件版本有误所导致，因此请问可否提供requirements.txt呢?谢谢。

**Comment by azmiao** [comment]
哦依赖文件忘记移过来了，我一会补上，另外你这个错误不是依赖的问题，请问你是最新的代码嘛，如果是的话那你是新配置文件还是旧配置文件呢

**Comment by azmiao** [comment]
哦msgpack序列化的包可能有依赖要求，一会我传一下依赖文件吧

**Comment by willy9156** [comment]
是最新的代码哦，也是用新配置档，昨天开帐号，有打到开好友功能

**Comment by azmiao** [comment]
> 是最新的代码哦，也是用新配置档，昨天开帐号，有打到开好友功能

依赖补上了，之前忘记迁移了23333

**Comment by willy9156** [comment]
感谢，不过稍早有试过pcrjjc3-tw的requirements.txt，和刚补上的requirements.txt是一样的，同样卡在`msgpack.exceptions.ExtraData: unpack(b) received extra data.` 的错误

我是单独执行query函式:
```python
if __name__ == '__main__':
    from asyncio import run
    print(run(query("3501408284")))
```

结果就跑出以下错误:
```python
C:\Users\willy\PycharmProjects\test\venv_310\Scripts\python.exe C:\Users\willy\PycharmProjects\test\main.py 
[2023-08-09 07:38:07,951 config] INFO: Succeeded to load config of "groupmaster"
[2023-08-09 07:38:07,951 config] WARNING: Not found config of "botmanage"
[2023-08-09 07:38:07,951 config] INFO: Succeeded to load config of "pcrclanbattle"
[2023-08-09 07:38:07,951 config] WARNING: Not found config of "dice"
[2023-08-09 07:38:07,952 config] INFO: Succeeded to load config of "priconne"
C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2023-08-09 07:38:08,533 hoshino] ERROR: 缺少图片资源：./res/img\priconne\gadget\equip.png
[2023-08-09 07:38:08,533 chara] ERROR: [Errno 2] No such file or directory: './res/img\\priconne\\gadget\\equip.png'
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\test\hoshino\modules\priconne\chara.py", line 19, in <module>
    gadget_equip = R.img('priconne/gadget/equip.png').open()
  File "C:\Users\willy\PycharmProjects\test\hoshino\R.py", line 50, in open
    return Image.open(self.path)
  File "C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img\\priconne\\gadget\\equip.png'
[2023-08-09 07:38:08,570 chara] WARNING: priconne.chara.Roster: 出现重名圣骑于id1242与id1034
[2023-08-09 07:38:08,571 chara] WARNING: priconne.chara.Roster: 出现重名菲欧于id1901与id1230
[2023-08-09 07:38:08,828 hoshino] INFO: 当前[台服其他服]账号配置文件使用的是【新版】用户文件
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\test\main.py", line 676, in <module>
    print(run(query("3501408284")))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\willy\PycharmProjects\test\main.py", line 189, in query
    await cur_client.callapi('/load/index', {'carrier': 'Android'})
  File "C:\Users\willy\PycharmProjects\test\pcr_client.py", line 162, in callapi
    response = self.unpack(response)[0]
  File "C:\Users\willy\PycharmProjects\test\pcr_client.py", line 125, in unpack
    return unpackb(dec,
  File "msgpack\_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

Process finished with exit code 1
```

**Comment by azmiao** [comment]
> 

我去借个新版配置文件看看

**Comment by azmiao** [comment]
我这边测试上次更新之后的建的号新版文件能用，不知道最近是不是又有更新了？方便看一下你的配置文件有多少行吗

**Comment by willy9156** [comment]
好的，有154行。
昨天开4服新帐，主线打到2-9开好友功能就直接拿配置文件来用了

**Comment by willy9156** [comment]
> > 好的，有154行。 昨天开4服新帐，主线打到2-9开好友功能就直接拿配置文件来用了 
> 
> 好像有点变化，我校验下，不过建议你吧这个附件删了，github上传出来还是有安全风险的

好的，感谢提醒，这边先删了。
再麻烦您了，谢谢!

**Comment by azmiao** [comment]
请问方便再看看你游戏内的uid是几位数吗，现在正常应该都是10位数，但我这看你配置文件里的UID是9位数了

**Comment by azmiao** [comment]
另外方便告知一下这个新号的游戏id吗

**Comment by willy9156** [comment]
游戏内是10码的，不过稍早不小心把share_perfs给删了，抱歉
我现在重新开一个新的模拟器重装游戏好了，原本用现有模拟器复制出来开新帐号

**Comment by azmiao** [comment]
> 

好的，看样子就是游戏又改了新的配置内容导致不兼容了

**Comment by azmiao** [comment]
我这测试用最新的游戏，去登录我以前创建的账号，生成的配置文件是和前几个月v4.0.0大版本更新完的配置内容格式一样的，但不知道为什么你这个新号生成的配置文件格式不太一样

**Comment by willy9156** [comment]
抱歉久等了，后来模拟器换成bluestack5重装，msgpack错误没了，不过改报 `failed code = 501, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}`

```python
C:\Users\willy\PycharmProjects\test\venv_310\Scripts\python.exe C:\Users\willy\PycharmProjects\test\main.py 
[2023-08-09 13:27:09,090 config] INFO: Succeeded to load config of "groupmaster"
[2023-08-09 13:27:09,090 config] WARNING: Not found config of "dice"
[2023-08-09 13:27:09,092 config] INFO: Succeeded to load config of "priconne"
[2023-08-09 13:27:09,092 config] INFO: Succeeded to load config of "pcrclanbattle"
[2023-08-09 13:27:09,092 config] WARNING: Not found config of "botmanage"
C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2023-08-09 13:27:09,567 hoshino] ERROR: 缺少图片资源：./res/img\priconne\gadget\equip.png
[2023-08-09 13:27:09,567 chara] ERROR: [Errno 2] No such file or directory: './res/img\\priconne\\gadget\\equip.png'
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\test\hoshino\modules\priconne\chara.py", line 19, in <module>
    gadget_equip = R.img('priconne/gadget/equip.png').open()
  File "C:\Users\willy\PycharmProjects\test\hoshino\R.py", line 50, in open
    return Image.open(self.path)
  File "C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img\\priconne\\gadget\\equip.png'
[2023-08-09 13:27:09,596 chara] WARNING: priconne.chara.Roster: 出现重名圣骑于id1242与id1034
[2023-08-09 13:27:09,598 chara] WARNING: priconne.chara.Roster: 出现重名菲欧于id1901与id1230
[2023-08-09 13:27:09,795 hoshino] INFO: 当前[台服其他服]账号配置文件使用的是【旧版】用户文件
pcr_client: /load/index api failed code = 501, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}
[2023-08-09 13:27:09,916 pcrjjc_tw_new] ERROR: 登录超时或失败，将尝试一次重新登录，正在重新登录...
pcr_client: /check/check_agreement api called
pcr_client: /check/game_start api called
pcr_client: /load/index api failed code = 501, {'status': 3, 'title': '伺服器錯誤', 'message': '遊戲發生錯誤。\\n即將返回標題畫面。'}
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\test\main.py", line 676, in <module>
    print(run(query("4411636368")))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\willy\PycharmProjects\test\main.py", line 193, in query
    await cur_client.login()
  File "C:\Users\willy\PycharmProjects\test\pcr_client.py", line 189, in login
    await self.callapi('/load/index', {
  File "C:\Users\willy\PycharmProjects\test\pcr_client.py", line 176, in callapi
    raise ApiException(data['message'], data['status'])
pcr_client.ApiException: 遊戲發生錯誤。\n即將返回標題畫面。

Process finished with exit code 1
```

**Comment by azmiao** [comment]
501错误我不记得是啥了，看起来游戏已经能够通过接口登录了，但获取账号信息的时候出错了，话说你不是换了新的游戏客户端，再印继账号登录的吗，这样生成的文件应该是新版的文件，为什么显示的是旧版用户文件呢

**Comment by willy9156** [comment]
对的，换新客户并引继账号登录，也依旧显示旧版。后来报错501的帐号是半年之前开帐的，不知会不会有点关联

**Comment by azmiao** [comment]
额，不应该啊，换新客户端引继账号登录应该会生成新版文件的；旧的账户在旧的客户端登录，然后升级客户端时才不会更新配置，只有重新引继才会变成新版文件。现在我这边没办法复现出你的情况，不方便排查。然后问下你那个新号还是msgpack报错吗，那个新号解锁好友后有去点进加好友的界面后再拿配置文件吗

**Comment by azmiao** [comment]
> 对的，换新客户并引继账号登录，也依旧显示旧版。后来报错501的帐号是半年之前开帐的，不知会不会有点关联

哦我想起个事，501好像是某个唯一的id冲突，如果我没记错的话，同一个设备的这个id是不会变的，也就是如果你再同一个模拟器里先登录了账号A，取出账号A的配置，这时候换账号B登录后，再使用账号A的配置进行查询就会501，不是很确定哈，我记得好像有这茬

**Comment by willy9156** [comment]
> 额，不应该啊，换新客户端引继账号登录应该会生成新版文件的；旧的账户在旧的客户端登录，然后升级客户端时才不会更新配置，只有重新引继才会变成新版文件。现在我这边没办法复现出你的情况，不方便排查。然后问下你那个新号还是msgpack报错吗，那个新号解锁好友后有去点进加好友的界面后再拿配置文件吗

先前msgpack报错，我确实只解锁好友就拿配置档了

> > 对的，换新客户并引继账号登录，也依旧显示旧版。后来报错501的帐号是半年之前开帐的，不知会不会有点关联
> 
> 哦我想起个事，501好像是某个唯一的id冲突，如果我没记错的话，同一个设备的这个id是不会变的，也就是如果你再同一个模拟器里先登录了账号A，取出账号A的配置，这时候换账号B登录后，再使用账号A的配置进行查询就会501，不是很确定哈，我记得好像有这茬

新装的模拟器，我先开新号，解锁好友就拿配置档，结果msgpack报错；
后来想说绑个帐号或许可行，才发现帐号已经有个85等的旧帐，于是开旧帐(有加好友)之后去取配置档，msgpack报错没了，改报错501了。
我直接重开一个新的模拟器，直接引继旧帐来试好了

**Comment by azmiao** [comment]
> 

你先试试吧，过几天有空我去创个新号试试

**Comment by willy9156** [comment]
好的，感谢您:thumbsup:

**Comment by willy9156** [comment]
重开一个新的模拟器直接引继旧帐，结果跑出其他error。
您是使用哪款模拟器呢?我想安装试试，再不行我应该就放弃了。

```python
C:\Users\willy\PycharmProjects\test\venv_310\Scripts\python.exe C:\Users\willy\PycharmProjects\test\main.py 
[2023-08-09 18:05:48,526 config] WARNING: Not found config of "botmanage"
[2023-08-09 18:05:48,526 config] INFO: Succeeded to load config of "pcrclanbattle"
[2023-08-09 18:05:48,527 config] INFO: Succeeded to load config of "groupmaster"
[2023-08-09 18:05:48,527 config] INFO: Succeeded to load config of "priconne"
[2023-08-09 18:05:48,527 config] WARNING: Not found config of "dice"
C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2023-08-09 18:05:49,185 hoshino] ERROR: 缺少图片资源：./res/img\priconne\gadget\equip.png
[2023-08-09 18:05:49,186 chara] ERROR: [Errno 2] No such file or directory: './res/img\\priconne\\gadget\\equip.png'
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\test\hoshino\modules\priconne\chara.py", line 19, in <module>
    gadget_equip = R.img('priconne/gadget/equip.png').open()
  File "C:\Users\willy\PycharmProjects\test\hoshino\R.py", line 50, in open
    return Image.open(self.path)
  File "C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img\\priconne\\gadget\\equip.png'
[2023-08-09 18:05:49,221 chara] WARNING: priconne.chara.Roster: 出现重名圣骑于id1242与id1034
[2023-08-09 18:05:49,223 chara] WARNING: priconne.chara.Roster: 出现重名菲欧于id1901与id1230
[2023-08-09 18:05:49,461 hoshino] INFO: 当前[台服其他服]账号配置文件使用的是【旧版】用户文件
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\test\main.py", line 676, in <module>
    print(run(query("4411636368")))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\willy\PycharmProjects\test\main.py", line 189, in query
    await cur_client.callapi('/load/index', {'carrier': 'Android'})
  File "C:\Users\willy\PycharmProjects\test\pcr_client.py", line 159, in callapi
    response = self.unpack(response)[0]
  File "C:\Users\willy\PycharmProjects\test\pcr_client.py", line 124, in unpack
    return unpackb(dec, strict_map_key=False ), data[-32:]
  File "C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\msgpack\fallback.py", line 129, in unpackb
    ret = unpacker._unpack()
  File "C:\Users\willy\PycharmProjects\test\venv_310\lib\site-packages\msgpack\fallback.py", line 681, in _unpack
    obj = obj.decode("utf_8", self._unicode_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 0: invalid continuation byte
```

**Comment by azmiao** [comment]
我那个是几年前拿的配置了😂😂，不记得用的啥模拟器了，下午测试是直接用的手机拿配置测试的，方便把你的配置私发我一份吗，xiaxing88@163.com，我明天有空的时候试试你这个

**Comment by willy9156** [comment]
> 我那个是几年前拿的配置了😂😂，不记得用的啥模拟器了，下午测试是直接用的手机拿配置测试的，方便把你的配置私发我一份吗，[xiaxing88@163.com](mailto:xiaxing88@163.com)，我明天有空的时候试试你这个

感谢，已传送。

**Comment by azmiao** [comment]
> > 我那个是几年前拿的配置了😂😂，不记得用的啥模拟器了，下午测试是直接用的手机拿配置测试的，方便把你的配置私发我一份吗，[xiaxing88@163.com](mailto:xiaxing88@163.com)，我明天有空的时候试试你这个
> 
> 感谢，已传送。

我这边查看了下你的配置文件，解析后发现游戏ID为4116669072，但我手动登录游戏后却搜索不到该ID，至少这个问题得先解决了才行

**Comment by willy9156** [comment]
应该是看viewer_id? 确实是4116669072，但游戏内显示是4411636368
![2023-08-10 10 49 21](https://github.com/azmiao/pcrjjc_tw_new/assets/54537848/4ed74331-1f37-4b70-baf1-d3559402aa8f)

**Comment by azmiao** [comment]
> 应该是看viewer_id? 确实是4116669072，但游戏内显示是4411636368 ![2023-08-10 10 49 21](https://user-images.githubusercontent.com/54537848/259607448-4ed74331-1f37-4b70-baf1-d3559402aa8f.jpg)

是viewer_id，原来这个字段就是游戏ID，看起来现在这个也改了

**Comment by azmiao** [comment]
我好像发现了什么端倪，配置里的`VIEWER_ID_highBits`由原来的0变成了1，高位补全，一会我再试试：
![image](https://github.com/azmiao/pcrjjc_tw_new/assets/54100327/e8dabb01-a98c-465d-b8c0-c45ebca366d0)

**Comment by azmiao** [comment]
`SHORT_UDID_highBits`也从原来的0变成1了，这个可能也要高位补全

**Comment by azmiao** [comment]
@willy9156 你现在再尝试一下看看，我更新了代码，我这边测试你的两个号好像都能查询了，`2e3087f7b29aa89b057119584501022017f15cc8`

**Comment by willy9156** [comment]
> @willy9156 你现在再尝试一下看看，我更新了代码，我这边测试你的两个号好像都能查询了，`2e3087f7b29aa89b057119584501022017f15cc8`

可以用了，感谢您!!
![image](https://github.com/azmiao/pcrjjc_tw_new/assets/54537848/31998f43-cd9c-4a9c-a3bb-6ac63dbb1a7a)

**Comment by azmiao** [comment]
OK
